### ISSUE TITLE
Sobre o posicionamento...

### ISSUE THREAD

**Issue by haru17** [kevenjesus/curso-certificacao-bootstrap#1]
Olá, **Keven Jesus**, estou vendo suas aulas sobre **Bootstrap 3**, e devo admitir que são muito boas. 
Gostaria de saber sobre o **posicionamento** com Bootstrap. Por exemplo:
```
<!-- Lista para menu-->
<div class="container">
<ul class="list-unstyled list-inline">
      <li>Item 1</li>
      <li>Item 2</li>
<ul>
</div>
```
Nesse caso como funciona para centralizar essa lista? Usaria `position`?

**Comment by kevenjesus** [comment]
Opa @haru17 basta adicionar `margin: auto` na UL

**Comment by haru17** [comment]
Fiz conforme você falou, no entanto a lista continuou na mesma posição:

```
<!-- Lista para menu-->
<div class="container">
<ul class="list-unstyled list-inline" margin=auto>
      <li>Item 1</li>
      <li>Item 2</li>
<ul>
</div>
```
Estou em um projeto escolar, e para criar um menu é necessário centralizá-lo, mas não consigo deixá-lo assim de forma alguma.

**Comment by kevenjesus** [comment]
Se não tiver uma largura definida ele não vai centralizar ...

**Comment by haru17** [comment]
Largura da ul? Certo então. Muito obrigado.

**Comment by kevenjesus** [comment]
Sim .. pq ate então ele tem 100% ... ou na ul ou no elemento pai dele :)
