### ISSUE TITLE
Atividade Workflow

### ISSUE THREAD

**Issue by YagoMatos02** [kevenjesus/curso-certificacao-bootstrap#187]
Boa tarde Keven,
Segue a atividade do 1° módulo
https://github.com/YagoMatos/atividade-workflow

**Comment by kevenjesus** [comment]
Opa @YagoMatos muito bom parabens :D só um detalhe o arquvo bower.json esta vazio e nao serve para nada

**Comment by YagoMatos02** [comment]
Sim, tinha ficado na dúvida se precisava constar ele, mas depois entendi, vlw cara!!
