### ISSUE TITLE
Atividade Workflow

### ISSUE THREAD

**Issue by ftbraian** [kevenjesus/curso-certificacao-bootstrap#31]
Fale Kevin, segue o link da minha atividade:

Note que as Tasks "mover css e html" estão redundante, pois as tasks de minificar já movem os arquivos, mas deixas as tarefas de mover apenas como exemplo já que pedia na atividade.

Grande Abraço!

https://github.com/ftbraian/atividade-workflow

**Comment by kevenjesus** [comment]
Opa @ftbraian, Enviei um pull-request para vc. 
As tasks de move nao precisam ... pois se as que minifica ja faz isso, então são inuteis no projeto.

Outra coisa que vc esqueceu do plugin para compilar o sass.

**Comment by ftbraian** [comment]
Ok, vou analisar as alterações! obrigado
